### ISSUE TITLE
Implement A Firebase Firestore DB

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/GrowPal-Web#1]
## About

When you go to `/sell` and enter your details to sell a product, this data goes nowhere and you get redirected back to the home page. Implement a firebase firestore database to store this data everytime submit is clicked. You'd be awarded extra points if you also make the homepage fetch from this database and show the items accordingly.

## Bounty 100

**Comment by bvgaurav4** [comment]
can u please assign me to this

**Comment by anuragrao04** [comment]
@bvgaurav4 Please go ahead!

**Comment by RishavSinha20** [comment]
please assign me

**Comment by anuragrao04** [comment]
@bvgaurav4 you have not shown any progress. You have 5 mins to show progress or I'll be forced to reassign

**Comment by anuragrao04** [comment]
You'll need firebase authentication keys for the same!

**Comment by anuragrao04** [comment]
@RishavSinha20 you can go ahead after 5 mins if @bvgaurav4 doesn't respond

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by sujay1844** [comment]
Can I get assigned to this?

**Comment by bvgaurav4** [comment]
did u guys get the api key for the firebase?

**Comment by anuragrao04** [comment]
@bvgaurav4 it says on the issue to approach the maintainer for API keys and other secrets

**Comment by sujay1844** [comment]
Please assign this issue to me if no progress is being made

**Comment by anuragrao04** [comment]
@sujay1844 go ahead

**Comment by rithulkamesh** [comment]
can i get assigned?
