### ISSUE TITLE
Implement An Authentication System With Firebase

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/GrowPal-Web#3]
## About

The current website has no authentication system (or a login system). We have no way of knowing who our user is and who's buying or selling anything. That isn't really a great thing. Implement an authentication layer using firebase `SignInWithPopUp()`. 

## Resources

This would require me to give you firebase API keys. Please approach the maintainer for these. API keys are meant to be kept secrets just like passwords and not to be put out in public, hence this process. 

## Bounty 100

**Comment by sujay1844** [comment]
Can I get assigned to this?

**Comment by anuragrao04** [comment]
@sujay1844 go ahead

**Comment by RishavSinha20** [comment]
please assign me

**Comment by rithulkamesh** [comment]
Assign
