### ISSUE TITLE
Edit Favicon

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/GrowPal-Web#4]
## About

The favicon (the image that applies next to your tab name) is the default one provided by svelte. Change this to something more appropriate. Approach the maintainer if you want a ready made `.png` asset file. This is a really really good first issue. 

## Bounty 20

**Comment by Ayush-gupta-dev** [comment]
I would like to work on this issue, @anuragrao04  pls assign me this issue

**Comment by Lohithsurya** [comment]
i would like to work on it, @anuragrao04 can u assign it to me

**Comment by avdhagam** [comment]
I want to work on this issue

**Comment by sid-nc** [comment]
i want to get assigned to this

**Comment by RishavSinha20** [comment]
please assign me this

**Comment by anuragrao04** [comment]
@Lohithsurya you have not made any update in the past 30 mins. This is getting reassigned to @avdhagam

**Comment by anuragrao04** [comment]
@avdhagam you've exceeded your 30 mins. Reassigning @Lohithsurya

**Comment by anuragrao04** [comment]
@Lohithsurya  please open a Pull request asap

**Comment by Lohithsurya** [comment]
okay i will do it now 

> @Lohithsurya please open a Pull request asap

i will do it right now

**Comment by Rohan123R** [comment]
@anuragrao04 can i get assigned to this and can i get a ready made png for it
